
const TYPES = {
    Subscribers: Symbol.for("Subscribers"),
    Connector: Symbol.for("Connector"),
    IndexRouter: Symbol.for("IndexRouter"),
    AuthRouter: Symbol.for("AuthRouter"),
    AuthController: Symbol.for("AuthController"),
    UserRouter: Symbol.for("UserRouter"),
    UserController: Symbol.for("UserController"),
    UserService: Symbol.for("UserService"),
    UserRepository: Symbol.for("UserRepository"),
    PostRouter: Symbol.for("PostRouter"),
    PostController: Symbol.for("PostController"),
    PostService: Symbol.for("PostService"),
    PostRepository: Symbol.for("PostRepository"),
    ProfileRouter: Symbol.for("ProfileRouter"),
    ProfileController: Symbol.for("ProfileController"),
    ProfileService: Symbol.for("ProfileService"),
    ProfileRepository: Symbol.for("ProfileRepository"),
    CommentRouter: Symbol.for("CommentRouter"),
    CommentController: Symbol.for("CommentController"),
    CommentService: Symbol.for("CommentService"),
    CommentRepository: Symbol.for("CommentRepository"),
    LikeRouter: Symbol.for("LikeRouter"),
    LikeController: Symbol.for("LikeController"),
    LikeService: Symbol.for("LikeService"),
    LikeRepository: Symbol.for("LikeRepository"),
    CommentRemasRouter: Symbol.for("CommentRemasRouter"),
    CommentRemasController: Symbol.for("CommentRemasController"),
    CommentRemasService: Symbol.for("CommentRemasService"),
    CommentRemasRepository: Symbol.for("CommentRemasRepository"),
    CategoryRouter: Symbol.for("CategoryRouter"),
    CategoryController: Symbol.for("CategoryController"),
    CategoryService: Symbol.for("CategoryService"),
    CategoryRepository: Symbol.for("CategoryRepository"),
    RemasLikeRouter: Symbol.for("RemasLikeRouter"),
    RemasLikeController: Symbol.for("RemasLikeController"),
    RemasLikeService: Symbol.for("RemasLikeService"),
    RemasLikeRepository: Symbol.for("RemasLikeRepository"),
    RegistrationMemberRemasRouter: Symbol.for("RegistrationMemberRemasRouter"),
    RegistrationMemberRemasController: Symbol.for("RegistrationMemberRemasController"),
    RegistrationMemberRemasService: Symbol.for("RegistrationMemberRemasService"),
    RegistrationMemberRemasRepository: Symbol.for("RegistrationMemberRemasRepository"),
    ProducerDispatcher: Symbol.for("ProducerDispatcher"),
    ConsumerDispatcher: Symbol.for("ConsumerDispatcher")
};

export { TYPES };